### ISSUE TITLE
can't start in docker

### ISSUE THREAD

**Issue by tommyvinny** [universonic/docker-stable-diffusion-webui#1]
can't start,i am sure models is good,as checkpoint and vae file in that directory,ckpt in Stable-diffusion,and .pt in VAE.has something wrong?
usage: launch.py [-h] [--data-dir DATA_DIR] [--config CONFIG] [--ckpt CKPT]
                 [--ckpt-dir CKPT_DIR] [--vae-dir VAE_DIR]
                 [--gfpgan-dir GFPGAN_DIR] [--gfpgan-model GFPGAN_MODEL]
                 [--no-half] [--no-half-vae] [--no-progressbar-hiding]
                 [--max-batch-count MAX_BATCH_COUNT]
                 [--embeddings-dir EMBEDDINGS_DIR]
                 [--textual-inversion-templates-dir TEXTUAL_INVERSION_TEMPLATES_DIR]
                 [--hypernetwork-dir HYPERNETWORK_DIR]
                 [--localizations-dir LOCALIZATIONS_DIR] [--allow-code]
                 [--medvram] [--lowvram] [--lowram]
                 [--always-batch-cond-uncond] [--unload-gfpgan]
                 [--precision {full,autocast}] [--upcast-sampling] [--share]
                 [--ngrok NGROK] [--ngrok-region NGROK_REGION]
                 [--enable-insecure-extension-access]
                 [--codeformer-models-path CODEFORMER_MODELS_PATH]
                 [--gfpgan-models-path GFPGAN_MODELS_PATH]
                 [--esrgan-models-path ESRGAN_MODELS_PATH]
                 [--bsrgan-models-path BSRGAN_MODELS_PATH]
                 [--realesrgan-models-path REALESRGAN_MODELS_PATH]
                 [--clip-models-path CLIP_MODELS_PATH] [--xformers]
                 [--force-enable-xformers] [--xformers-flash-attention]
                 [--deepdanbooru] [--opt-split-attention]
                 [--opt-sub-quad-attention]
                 [--sub-quad-q-chunk-size SUB_QUAD_Q_CHUNK_SIZE]
                 [--sub-quad-kv-chunk-size SUB_QUAD_KV_CHUNK_SIZE]
                 [--sub-quad-chunk-threshold SUB_QUAD_CHUNK_THRESHOLD]
                 [--opt-split-attention-invokeai] [--opt-split-attention-v1]
                 [--disable-opt-split-attention] [--disable-nan-check]
                 [--use-cpu USE_CPU [USE_CPU ...]] [--listen] [--port PORT]
                 [--show-negative-prompt] [--ui-config-file UI_CONFIG_FILE]
                 [--hide-ui-dir-config] [--freeze-settings]
Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
Commit hash: 21593c80822e4d477a62ab090fe144e7f611bc2f
Installing torch and torchvision
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
--------------------------------------------------------
| You are not up to date with the most recent release. |
| Consider running `git pull` to update.               |
--------------------------------------------------------
Launching Web UI with arguments: --xformers --listen --port 8080 -d
                 [--ui-settings-file UI_SETTINGS_FILE] [--gradio-debug]
                 [--gradio-auth GRADIO_AUTH]
                 [--gradio-img2img-tool GRADIO_IMG2IMG_TOOL]
                 [--gradio-inpaint-tool GRADIO_INPAINT_TOOL]
                 [--opt-channelslast] [--styles-file STYLES_FILE]
                 [--autolaunch] [--theme THEME] [--use-textbox-seed]
                 [--disable-console-progressbars] [--enable-console-prompts]
                 [--vae-path VAE_PATH] [--disable-safe-unpickle] [--api]
                 [--api-auth API_AUTH] [--api-log] [--nowebui]
                 [--ui-debug-mode] [--device-id DEVICE_ID] [--administrator]
                 [--cors-allow-origins CORS_ALLOW_ORIGINS]
                 [--cors-allow-origins-regex CORS_ALLOW_ORIGINS_REGEX]
                 [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE]
                 [--server-name SERVER_NAME] [--gradio-queue]
                 [--skip-version-check] [--no-hashing]
                 [--ldsr-models-path LDSR_MODELS_PATH] [--lora-dir LORA_DIR]
                 [--scunet-models-path SCUNET_MODELS_PATH]
                 [--swinir-models-path SWINIR_MODELS_PATH]
launch.py: error: unrecognized arguments: -d

**Comment by tommyvinny** [comment]
anther 
--------------------------------------------------------
| You are not up to date with the most recent release. |
| Consider running `git pull` to update.               |
--------------------------------------------------------
Launching Web UI with arguments: --xformers --listen --port 8080 --medvram
    import webui
  File "/app/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/app/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/app/stable-diffusion-webui/modules/shared.py", line 155, in <module>
    os.makedirs(cmd_opts.hypernetwork_dir, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/stable-diffusion-webui/models/hypernetworks'

**Comment by tommyvinny** [comment]
Installing requirements for Web UI
--------------------------------------------------------
| You are not up to date with the most recent release. |
| Consider running `git pull` to update.               |
--------------------------------------------------------
Launching Web UI with arguments: --xformers --listen --port 8080 --medvram
Loading weights [a074b8864e] from /app/stable-diffusion-webui/models/Stable-diffusion/CounterfeitV25_25.safetensors
Creating model from config: /app/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 6.6s (load weights from disk: 0.2s, create model: 1.1s, apply weights to model: 1.5s, apply half(): 0.9s, load VAE: 2.8s).
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/app/stable-diffusion-webui/launch.py", line 361, in <module>
    start()
  File "/app/stable-diffusion-webui/launch.py", line 356, in start
    webui.webui()
  File "/app/stable-diffusion-webui/webui.py", line 232, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started

**Comment by zoe224010** [comment]
add `fastapi==0.90.0` to "/app/stable-diffusion-webui/requirements_versions.txt"

**Comment by ac2522** [comment]
Tried  fastapi==0.91.0, 0.90.1 and 0.90.0. Still getting "Cannot add middleware after an application has started" error :(
