### ISSUE TITLE
 raise RuntimeError("Cannot add middleware after an application has started")

### ISSUE THREAD

**Issue by zoe224010** [universonic/docker-stable-diffusion-webui#2]
NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1
I want to add `fastapi==0.90.0` to "requirements_versions.txt",but I don't know where is it?

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################
################################################################
Running on sduser user
################################################################
################################################################
Create and activate python venv
################################################################
################################################################
Launching launch.py...
################################################################
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Collecting torch==1.13.1+cu117
  Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl (1801.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 GB 467.5 kB/s eta 0:00:00
Collecting torchvision==0.14.1+cu117
  Downloading https://download.pytorch.org/whl/cu117/torchvision-0.14.1%2Bcu117-cp310-cp310-linux_x86_64.whl (24.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.3/24.3 MB 11.6 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting numpy
  Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 26.0 MB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0
  Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 15.5 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.30.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 2.7 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 13.5 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.0/157.0 kB 3.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 1.9 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.0.2-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.2/123.2 kB 5.2 MB/s eta 0:00:00
Installing collected packages: urllib3, typing-extensions, pillow, numpy, idna, charset-normalizer, certifi, torch, requests, torchvision
Successfully installed certifi-2023.5.7 charset-normalizer-3.1.0 idna-3.4 numpy-1.24.3 pillow-9.5.0 requests-2.30.0 torch-1.13.1+cu117 torchvision-0.14.1+cu117 typing-extensions-4.5.0 urllib3-2.0.2
Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
Commit hash: 21593c80822e4d477a62ab090fe144e7f611bc2f
Installing torch and torchvision
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
version check failed 'commit'
Launching Web UI with arguments: --xformers --listen --port 8080 --medvram
Calculating sha256 for /app/stable-diffusion-webui/models/Stable-diffusion/lanmao37.safetensors: 635a6190a063731436ce19e0efdaf9b62e577934a378c9e3aff342a440d687c2
Loading weights [635a6190a0] from /app/stable-diffusion-webui/models/Stable-diffusion/lanmao37.safetensors
Creating model from config: /app/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.

Downloading (…)olve/main/vocab.json:   0%|          | 0.00/961k [00:00<?, ?B/s]
Downloading (…)olve/main/vocab.json: 100%|██████████| 961k/961k [00:00<00:00, 1.17MB/s]
Downloading (…)olve/main/vocab.json: 100%|██████████| 961k/961k [00:00<00:00, 1.17MB/s]

Downloading (…)olve/main/merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]
Downloading (…)olve/main/merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 815kB/s]
Downloading (…)olve/main/merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 814kB/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 389/389 [00:00<00:00, 3.96MB/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?B/s]
Downloading (…)okenizer_config.json: 100%|██████████| 905/905 [00:00<00:00, 9.68MB/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/4.52k [00:00<?, ?B/s]
Downloading (…)lve/main/config.json: 100%|██████████| 4.52k/4.52k [00:00<00:00, 34.4MB/s]
Checkpoint lanmao37.safetensors [635a6190a0] not found; loading fallback lanmao37.safetensors [635a6190a0]
Traceback (most recent call last):
  File "/app/stable-diffusion-webui/launch.py", line 361, in <module>
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 28.5s (calculate hash: 13.7s, load weights from disk: 0.8s, create model: 6.6s, apply weights to model: 4.3s, apply half(): 1.6s, load VAE: 1.4s).
Running on local URL:  http://0.0.0.0:8080
To create a public link, set `share=True` in `launch()`.
    start()
  File "/app/stable-diffusion-webui/launch.py", line 356, in start
    webui.webui()
  File "/app/stable-diffusion-webui/webui.py", line 232, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/applications.py", line 139, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")

**Comment by zoe224010** [comment]
Oh, I found it! /app/stable-diffusion-webui/requirements_versions.txt
